#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
CLEAR_COLOR='\033[0m'

function fail {
    echo -e "${RED}[error] $1${CLEAR_COLOR}"
    exit 1
}

if ! go build 2> /dev/null; then
    fail "build failed. review code and try again"
fi

echo -e "${GREEN}[success] ran pre-commit hook${CLEAR_COLOR}"
