name: goenv

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check Build and fmt
      run: ./.githooks/pre-commit

    - name: Test
      run: go test -timeout 30m ./...
